version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    volumes:
      - ./app/:/app/
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=aditya
      - DB_PASS=changeme
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=aditya
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: