# Generated by Django 3.2.25 on 2024-05-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desription',
            new_name='description',
        ),
    ]
